# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2

multi-ecosystem-groups:
  dependencies:
    schedule:
      interval: "monthly"

updates:
  - package-ecosystem: "npm"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: "dependencies"
    cooldown:
      default-days: 7

  - package-ecosystem: "github-actions"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: "dependencies"
    cooldown:
      default-days: 7
