name: Tests

on:
  pull_request_target:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
  workflow_dispatch:

jobs:
  test:
    name: WebPageTest Test Cases
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Install dependencies
        run: npm install

      - name: Run WebPageTest with unit tests
        run: npm test
        env:
          WPT_SERVER: "webpagetest.httparchive.org"
          WPT_API_KEY: ${{ secrets.HA_API_KEY }}

      - name: Run WebPageTest for more websites
        run: node tests/wpt.js
        env:
          WPT_SERVER: "webpagetest.httparchive.org"
          WPT_API_KEY: ${{ secrets.HA_API_KEY }}
          PR_BODY: ${{ github.event.pull_request.body }}

      - name: Upload artifact if needed
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: artifact.md

      - name: Add comment with results
        uses: mshick/add-pr-comment@v2
        if: always()
        with:
          refresh-message-position: true
          message-path: comment.md
