name: Tests

on:
  pull_request

jobs:
  test:
    name: WebPageTest Test Cases
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm install webpagetest && npm install jest

      - name: Run WebPageTest
        run: |
          EXPECTED_TESTS=$(for file in $(git diff --name-only --diff-filter=ACMRT \
            ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | \
            grep -E "^dist/.*\.js$"); do basename "$file"; done | cut -d\. -f1 | sort | uniq)

          TEST_JSON=""
          for TEST in ${EXPECTED_TESTS[@]}; do
            echo "::group::Running test: $TEST"
            if [ -f "tests/$TEST.test.js" ]; then
              CURRENT_RESULT=$(npm test $TEST)
              TEST_RESULTS="$TEST_RESULTS\n$CURRENT_RESULT"
            else
              echo "There are no test cases for $TEST"
              exit 2
            fi
            echo "::endgroup::"
          done

          echo "TEST_RESULTS=$TEST_RESULTS" >> $GITHUB_ENV
          echo $TEST_RESULTS >> $GITHUB_STEP_SUMMARY
        env:
          WPT_API_KEY: ${{ secrets.WPT_API_KEY }}

      - name: Test results
        run: |
          echo $TEST_RESULTS

      - name: Add PR Comment
        uses: mshick/add-pr-comment@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: |
            ${{ env.TEST_RESULTS }}

