name: Tests

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: WebPageTest Test Cases
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm install webpagetest && npm install jest

      - name: Run WebPageTest
        # continue-on-error: true
        run: |
          FILES=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} \
            ${{ github.event.pull_request.head.sha }} | grep -E "^dist/.*\.js$")
          CUSTOM_METRIC_FILES=("00_reset" "a11y" "almanac" "aurora" "cms" "css-variables" "css" \
            "ecommerce" "example" "fugu-apis" "javascript" "markup" "media" "observers" "origin-trials" \
            "parsed_css" "performance" "privacy" "pwa" "responsive_images" "robots_meta" "robots_txt" \
            "sass" "security" "structured-data" "third-parties" "valid-head" "well-known" "wpt_bodies")
          for FILE in $FILES; do

            TEST_NAME="${FILE%.test.js}"
            TEST_NAME="${TEST_NAME%.js}"

            for CM_FILE in "${CUSTOM_METRIC_FILES[@]}"; do
              if [[ $TEST_NAME == $CM_FILE ]]; then

                if [ -f "dist/$TEST_NAME.test.js" ]; then
                  echo "Running test: $TEST_NAME"
                  npm test $TEST_NAME
                else
                  echo "There are no test cases for $TEST_NAME"
                  exit 2
                fi
              fi
            done
          done
        env:
          WPT_API_KEY: ${{ secrets.WPT_API_KEY }}
