name: Tests

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'

jobs:
  test:
    name: WebPageTest Test Cases
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          npm install webpagetest
          npm install jest

      - name: Run WebPageTest for WebAlmanac website
        run: |
          echo "::group::Unit tests on https://almanac.httparchive.org/en/2022/"
            npm test
          echo "::endgroup::"
        env:
          WPT_API_KEY: ${{ secrets.WPT_API_KEY }}

      - name: Test more websites
        run: |
          METRICS=$(for file in $(git diff --name-only --diff-filter=ACMRT \
            ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | \
            grep -E "^dist/.*\.js$"); do basename "$file"; done | cut -d\. -f1 | sort | uniq)

          pr_body="${{ github.event.pull_request.body }}"
          echo "$pr_body"
          while IFS= read -r line; do
            lines+=("$line")
          done <<< pr_body

          start_index=-1
          for ((i=0; i<${#lines[@]}; i++)); do
              if [[ ${lines[$i]} == "**Test websites**:" ]]; then
                  start_index=$((i + 2))  # Start from this line
                  break
              fi
          done

          declare -a URLS
          url_pattern="^(http|https|ftp)://[a-zA-Z0-9.-]+(\.[a-zA-Z]{2,4})(/[a-zA-Z0-9_.-]+)*(\/?)(\?[a-zA-Z0-9_.-]+=[a-zA-Z0-9%_.-]+)*)?$"
          for ((i=start_index; i<${#lines[@]}; i++)); do
              echo $i
              url="${lines[$i]}"
              url="${url//- /}"
              if [[ $url =~ $url_pattern ]]; then
                  URLS+=("$url")
              fi
          done

          for URL in ${URLS[@]}; do
            echo "::group::Custom metrics for $URL"
              node tests/wpt.js $URL "$METRICS"
            echo "::endgroup::"
          done
        env:
          WPT_API_KEY: ${{ secrets.WPT_API_KEY }}

      - name: Add comment with results
        uses: mshick/add-pr-comment@v2
        if: always()
        with:
          refresh-message-position: true
          message-path: test-results.md
