name: Tests

on:
  pull_request_target:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
  workflow_dispatch:

jobs:
  test:
    name: WebPageTest Test Cases
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: "Fetch PR changes (Internal branch: full checkout)"
        if: |
          github.event_name == 'pull_request_target' &&
          github.event.pull_request.head.repo.full_name == github.repository
        run: |
          git fetch origin ${{ github.event.pull_request.head.sha }}
          git checkout ${{ github.event.pull_request.head.sha }}

      - name: "Fetch PR changes (Fork PR: dist/ only)"
        if: |
          github.event_name == 'pull_request_target' &&
          github.event.pull_request.head.repo.full_name != github.repository
        run: |
          git fetch origin ${{ github.event.pull_request.head.sha }}
          git checkout ${{ github.event.pull_request.head.sha }} -- dist/

      - name: Install dependencies
        run: npm install jest webpagetest

      - name: Run WebPageTest with unit tests
        run: npm test
        env:
          WPT_SERVER: "webpagetest.httparchive.org"
          WPT_API_KEY: ${{ secrets.HA_API_KEY }}

      - name: Run WebPageTest for more websites
        run: node tests/wpt.js
        env:
          WPT_SERVER: "webpagetest.httparchive.org"
          WPT_API_KEY: ${{ secrets.HA_API_KEY }}
          PR_BODY: ${{ github.event.pull_request.body }}

      - name: Add comment to PR
        uses: mshick/add-pr-comment@v3
        if: always() && hashFiles('comment.md') != ''
        with:
          refresh-message-position: true
          message-path: comment.md
