name: Tests

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: WebPageTest Test Cases
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm install webpagetest && npm install jest

      - name: Run WebPageTest
        run: |
          EXPECTED_TESTS=$(for file in $(git diff --name-only --diff-filter=ACMRT \
            ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | \
            grep -E "^dist/.*\.js$"); do basename "$file"; done | cut -d\. -f1 | sort | uniq)

          for TEST in ${EXPECTED_TESTS[@]}; do
            echo "Running test: $TEST"
            if [ -f "tests/$TEST.test.js" ]; then
              npm test $TEST
            else
              echo "There are no test cases for $TEST"
              exit 2
            fi
          done
        env:
          WPT_API_KEY: ${{ secrets.WPT_API_KEY }}
