name: Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: WebPageTest Test Cases
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          npm install webpagetest
          npm install jest

      - name: Run WebPageTest
        run: |
          EXPECTED_TESTS=$(for file in $(git diff --name-only --diff-filter=ACMRT \
            ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | \
            grep -E "^dist/.*\.js$"); do basename "$file"; done | cut -d\. -f1 | sort | uniq)

          for TEST in ${EXPECTED_TESTS[@]}; do
            echo "::group::Test case for $TEST"
            if [ -f "tests/$TEST.test.js" ]; then
              npm test $TEST
            else
              echo "Test case file tests/$TEST.test.js not found"
              exit 2
            fi
            echo "::endgroup::"
          done
        env:
          WPT_API_KEY: ${{ secrets.WPT_API_KEY }}

      - name: Add comment with results
        uses: mshick/add-pr-comment@v2
        if: always()
        with:
          refresh-message-position: true
          message-path: test-results.txt
